import request from 'supertest';
import { createApp } from '../src/app';
import { connectDB, disconnectDB } from '../src/db/connection';
import { ensureRbacSeeded } from '../src/rbac/seedRbac';
import { User } from '../src/models/User';
import { SalaryAdvance } from '../src/models/SalaryAdvance';
import { LedgerEntry } from '../src/models/LedgerEntry';
import { hashPassword } from '../src/utils/password';
import { redis } from '../src/config/redis';
import { mailerQueue } from '../src/jobs/mailer.queue';
import { asSystem } from './helpers/as-system';
import { buildFixture, type CrossTenantFixture } from './cross-tenant/fixture';

/**
 * Fees, payroll and the finance ledger: the money rules. Tenant isolation for
 * these models and endpoints is generated by the cross-tenant registry; this
 * file covers behaviour inside a school, plus the self-scoped and multi-step
 * paths the generic probes can't express.
 */
const app = createApp();
let fx: CrossTenantFixture;

const auth = (token: string) => ({ Authorization: `Bearer ${token}` });
const A = () => auth(fx.a.token);
const api = (path: string) => `/api/v1${path}`;

async function signIn(email: string, password: string): Promise<string> {
  await asSystem(async () =>
    User.updateOne({ email }, { $set: { passwordHash: await hashPassword(password), mustChangePassword: false } }),
  );
  const res = await request(app).post(api('/auth/login')).send({ email, password }).expect(200);
  return res.body.data.accessToken as string;
}

let classId: string;
let sectionId: string;
let tuitionHead: string;
let examHead: string;
let studentA: string;
let studentB: string;

beforeAll(async () => {
  await connectDB();
  await ensureRbacSeeded();
  fx = await buildFixture(app);

  await request(app)
    .post(api('/academic-sessions'))
    .set(A())
    .send({ name: '2026-2027', startDate: '2026-04-01', endDate: '2027-03-31', isCurrent: true })
    .expect(201);
  classId = (await request(app).post(api('/classes')).set(A()).send({ name: 'Grade 4' }).expect(201)).body.data._id;
  sectionId = (await request(app).post(api('/sections')).set(A()).send({ classId, name: 'A' }).expect(201)).body.data._id;

  const admit = async (firstName: string, guardian: Record<string, unknown>) =>
    (
      await request(app)
        .post(api('/students'))
        .set(A())
        .send({
          firstName,
          lastName: 'Finance',
          dateOfBirth: '2016-05-05',
          gender: 'FEMALE',
          classId,
          sectionId,
          guardians: [{ lastName: 'Finance', phone: '+1-555-7777', relation: 'MOTHER', ...guardian }],
        })
        .expect(201)
    ).body.data._id as string;
  studentA = await admit('Amira', { firstName: 'Mona', email: `mona-${Date.now()}@finance.test`, createLogin: true });
  studentB = await admit('Bilal', { firstName: 'Nadia' });

  tuitionHead = (await request(app).post(api('/fees/heads')).set(A()).send({ name: 'Tuition', code: 'TUI', frequency: 'MONTHLY' }).expect(201)).body.data._id;
  examHead = (await request(app).post(api('/fees/heads')).set(A()).send({ name: 'Exam fee', code: 'EXM', frequency: 'ANNUAL' }).expect(201)).body.data._id;
  await request(app)
    .post(api('/fees/structures'))
    .set(A())
    .send({ name: 'Grade 4 fees', classId, items: [{ feeHeadId: tuitionHead, amountMinor: 10000 }, { feeHeadId: examHead, amountMinor: 3000 }] })
    .expect(201);
  // 50% scholarship on tuition only, for student B.
  await request(app)
    .post(api('/fees/concessions'))
    .set(A())
    .send({ studentId: studentB, name: 'Merit scholarship', kind: 'SCHOLARSHIP', type: 'PERCENT', value: 50, feeHeadId: tuitionHead })
    .expect(201);
}, 180_000);

afterAll(async () => {
  await disconnectDB();
  await mailerQueue.close();
  redis.disconnect();
});

describe('Family roles hold no school-wide reads (security regression)', () => {
  it('a parent is refused the student, guardian and invoice lists', async () => {
    const dues = await request(app).get(api(`/fees/students/${studentA}/dues`)).set(A()).expect(200);
    const email = dues.body.data.student.guardians[0].guardianId.email as string;
    const parent = await signIn(email, 'Parent123!');
    for (const path of ['/students', '/guardians', '/fees/invoices']) {
      await request(app).get(api(path)).set(auth(parent)).expect(403);
    }
  });

  it('a second fee structure for the same class and session is refused', async () => {
    await request(app)
      .post(api('/fees/structures'))
      .set(A())
      .send({ name: 'Duplicate', classId, items: [{ feeHeadId: tuitionHead, amountMinor: 1 }] })
      .expect(409);
  });
});

describe('Invoice generation', () => {
  const run = { classIds: [] as string[], periodKey: '2026-09', periodLabel: 'September 2026', dueDate: '2026-09-10' };

  it('previews exactly what it will bill, with concessions applied', async () => {
    run.classIds = [classId];
    const res = await request(app).post(api('/fees/invoices/preview')).set(A()).send(run).expect(200);
    expect(res.body.data.invoiceCount).toBe(2);
    // A: 10000 + 3000; B: 5000 (50% off tuition) + 3000.
    expect(res.body.data.totalMinor).toBe(13000 + 8000);
  });

  it('generates numbered invoices once, and refuses to bill the same period twice', async () => {
    const res = await request(app).post(api('/fees/invoices/generate')).set(A()).send(run).expect(201);
    expect(res.body.data.invoiceCount).toBe(2);
    await request(app).post(api('/fees/invoices/generate')).set(A()).send(run).expect(400);

    const list = await request(app).get(api(`/fees/invoices?periodKey=2026-09`)).set(A()).expect(200);
    const invoices = list.body.data.items as { invoiceNumber: string; totalMinor: number; studentId: { _id: string } }[];
    expect(invoices).toHaveLength(2);
    for (const inv of invoices) expect(inv.invoiceNumber).toMatch(/^INV-2026-\d{5}$/);
    const b = invoices.find((i) => i.studentId._id === studentB)!;
    expect(b.totalMinor).toBe(8000);
  });

  it('lets a discount reduce but never exceed the balance', async () => {
    const dues = await request(app).get(api(`/fees/students/${studentB}/dues`)).set(A()).expect(200);
    const invoiceId = dues.body.data.invoices[0]._id as string;
    await request(app).post(api(`/fees/invoices/${invoiceId}/adjustments`)).set(A()).send({ type: 'DISCOUNT', amountMinor: 9000, reason: 'Too much' }).expect(400);
    const ok = await request(app).post(api(`/fees/invoices/${invoiceId}/adjustments`)).set(A()).send({ type: 'DISCOUNT', amountMinor: 1000, reason: 'Hardship' }).expect(200);
    expect(ok.body.data.totalMinor).toBe(7000);
  });
});

describe('Payments, refunds and reversals', () => {
  let invoiceId: string;
  let paymentId: string;

  it('collects part of a bill once, even if the request is retried', async () => {
    const dues = await request(app).get(api(`/fees/students/${studentA}/dues`)).set(A()).expect(200);
    invoiceId = dues.body.data.invoices[0]._id;
    expect(dues.body.data.totalDueMinor).toBe(13000);

    const body = { studentId: studentA, amountMinor: 5000, method: 'CASH', idempotencyKey: `collect-${Date.now()}` };
    const first = await request(app).post(api('/fees/payments')).set(A()).send(body).expect(201);
    const retry = await request(app).post(api('/fees/payments')).set(A()).send(body).expect(201);
    expect(retry.body.data._id).toBe(first.body.data._id);
    expect(first.body.data.receiptNumber).toMatch(/^RCPT-\d{4}-\d{5}$/);
    paymentId = first.body.data._id;

    const inv = await request(app).get(api(`/fees/invoices/${invoiceId}`)).set(A()).expect(200);
    expect(inv.body.data.paidMinor).toBe(5000);
    expect(inv.body.data.status).toBe('PARTIALLY_PAID');
  });

  it('refuses to take more than is owed', async () => {
    await request(app).post(api('/fees/payments')).set(A()).send({ studentId: studentA, amountMinor: 8001, method: 'CASH' }).expect(400);
  });

  it('won’t cancel an invoice that has money against it', async () => {
    await request(app).post(api(`/fees/invoices/${invoiceId}/cancel`)).set(A()).send({ reason: 'Wrong class' }).expect(409);
  });

  it('refunds part of a payment, then reverses the rest, restoring the balance', async () => {
    const refund = await request(app).post(api(`/fees/payments/${paymentId}/refund`)).set(A()).send({ amountMinor: 2000, reason: 'Overcharged', method: 'CASH' }).expect(200);
    expect(refund.body.data.netMinor).toBe(3000);
    let inv = await request(app).get(api(`/fees/invoices/${invoiceId}`)).set(A()).expect(200);
    expect(inv.body.data.paidMinor).toBe(3000);

    await request(app).post(api(`/fees/payments/${paymentId}/refund`)).set(A()).send({ amountMinor: 3001, reason: 'Too much', method: 'CASH' }).expect(400);
    const reversed = await request(app).post(api(`/fees/payments/${paymentId}/reverse`)).set(A()).send({ reason: 'Cheque bounced' }).expect(200);
    expect(reversed.body.data.status).toBe('REVERSED');
    inv = await request(app).get(api(`/fees/invoices/${invoiceId}`)).set(A()).expect(200);
    expect(inv.body.data.paidMinor).toBe(0);
    expect(inv.body.data.status).toBe('UNPAID');
  });

  it('pays off the invoice in full', async () => {
    const res = await request(app).post(api('/fees/payments')).set(A()).send({ studentId: studentA, amountMinor: 13000, method: 'BANK_TRANSFER' }).expect(201);
    expect(res.body.data.allocations[0].invoiceId.status).toBe('PAID');
  });

  it("can't collect against another school's student", async () => {
    await request(app).post(api('/fees/payments')).set(auth(fx.b.token)).send({ studentId: studentB, amountMinor: 100, method: 'CASH' }).expect(400);
  });
});

describe('Late fines, defaulters and reports', () => {
  it('applies the per-day rule once, capped, without stacking on re-runs', async () => {
    await request(app).patch(api('/fees/settings')).set(A()).send({ lateFineType: 'PER_DAY', lateFineAmountMinor: 100, graceDays: 0, maxFineMinor: 700 }).expect(200);
    const due = new Date(Date.now() - 10 * 86_400_000).toISOString().slice(0, 10);
    const inv = await request(app)
      .post(api('/fees/invoices'))
      .set(A())
      .send({ studentId: studentB, lines: [{ name: 'Library', amountMinor: 2000 }], periodLabel: 'Library fee', dueDate: due, applyConcessions: false })
      .expect(201);

    const first = await request(app).post(api('/fees/invoices/apply-late-fines')).set(A()).expect(200);
    expect(first.body.data.invoicesFined).toBeGreaterThanOrEqual(1);
    let fined = await request(app).get(api(`/fees/invoices/${inv.body.data._id}`)).set(A()).expect(200);
    expect(fined.body.data.lateFineMinor).toBe(700); // 10 days × 100, capped at 700
    expect(fined.body.data.totalMinor).toBe(2700);

    await request(app).post(api('/fees/invoices/apply-late-fines')).set(A()).expect(200);
    fined = await request(app).get(api(`/fees/invoices/${inv.body.data._id}`)).set(A()).expect(200);
    expect(fined.body.data.totalMinor).toBe(2700);
  });

  it('lists the student as a defaulter and reports collections net of refunds', async () => {
    const defaulters = await request(app).get(api('/fees/defaulters')).set(A()).expect(200);
    const row = (defaulters.body.data.items as { _id: string; overdueMinor: number }[]).find((d) => d._id === studentB);
    expect(row?.overdueMinor).toBeGreaterThan(0);

    const today = new Date().toISOString().slice(0, 10);
    const report = await request(app).get(api(`/fees/reports/collections?from=${today}&to=${today}`)).set(A()).expect(200);
    // 13000 paid in full; the 5000 payment was refunded/reversed and is excluded.
    expect(report.body.data.totalMinor).toBe(13000);
  });
});

describe('Payroll', () => {
  let teacherEmail: string;
  let employeeId: string;
  let runId: string;

  it('computes, reviews, locks and publishes a month, recovering an advance', async () => {
    teacherEmail = `payroll-${Date.now()}@finance.test`;
    const teacher = await request(app).post(api('/teachers')).set(A()).send({ firstName: 'Tariq', lastName: 'Payroll', email: teacherEmail, joiningDate: '2025-01-01' }).expect(201);
    employeeId = teacher.body.data.employee._id;

    const hra = (await request(app).post(api('/payroll/components')).set(A()).send({ name: 'House rent', code: 'HRA', type: 'EARNING', calculation: 'PERCENT_OF_BASIC', defaultValue: 40 }).expect(201)).body.data._id;
    const pf = (await request(app).post(api('/payroll/components')).set(A()).send({ name: 'Provident fund', code: 'PF', type: 'DEDUCTION', calculation: 'PERCENT_OF_BASIC', defaultValue: 5 }).expect(201)).body.data._id;
    const tax = (await request(app).post(api('/payroll/components')).set(A()).send({ name: 'Income tax', code: 'TAX', type: 'DEDUCTION', calculation: 'PERCENT_OF_GROSS', defaultValue: 10 }).expect(201)).body.data._id;
    await request(app).post(api('/payroll/components')).set(A()).send({ name: 'Bad', code: 'BAD', type: 'EARNING', calculation: 'PERCENT_OF_GROSS', defaultValue: 5 }).expect(400);

    await request(app)
      .post(api('/payroll/structures'))
      .set(A())
      .send({ employeeId, basicMinor: 100000, components: [{ componentId: hra, value: 40 }, { componentId: pf, value: 5 }, { componentId: tax, value: 10 }], accountNumber: 'PK00TEST' })
      .expect(201);
    await request(app).post(api('/payroll/advances')).set(A()).send({ employeeId, amountMinor: 20000, installmentMinor: 5000 }).expect(201);

    const run = await request(app).post(api('/payroll/runs')).set(A()).send({ month: '2026-09' }).expect(201);
    runId = run.body.data._id;
    const slip = (run.body.data.payslips as { _id: string; employeeId: string; grossMinor: number; netMinor: number }[]).find((p) => p.employeeId === employeeId)!;
    // gross 100000 + 40000; PF 5000; tax 10% of gross 14000; advance 5000 → net 116000.
    expect(slip.grossMinor).toBe(140000);
    expect(slip.netMinor).toBe(116000);

    // 3 unpaid days of 30: 140000 / 30 × 3 = 14000 more off.
    const reviewed = await request(app).patch(api(`/payroll/payslips/${slip._id}`)).set(A()).send({ unpaidLeaveDays: 3, adjustments: [{ label: 'Bonus', amountMinor: 1000 }] }).expect(200);
    expect(reviewed.body.data.netMinor).toBe(116000 - 14000 + 1000);

    await request(app).post(api(`/payroll/runs/${runId}/publish`)).set(A()).expect(409); // must lock first
    await request(app).post(api(`/payroll/runs/${runId}/lock`)).set(A()).expect(200);
    await request(app).patch(api(`/payroll/payslips/${slip._id}`)).set(A()).send({ unpaidLeaveDays: 0 }).expect(409);
    const advance = await asSystem(() => SalaryAdvance.findOne({ employeeId }).lean());
    expect(advance?.recoveredMinor).toBe(5000);

    const csv = await request(app).get(api(`/payroll/runs/${runId}/bank-export`)).set(A()).expect(200);
    expect(csv.headers['content-type']).toContain('text/csv');
    expect(csv.text).toContain('PK00TEST');

    const published = await request(app).post(api(`/payroll/runs/${runId}/publish`)).set(A()).expect(200);
    const posted = await asSystem(() => LedgerEntry.findOne({ sourceId: runId }).lean());
    expect(posted?.amountMinor).toBe(published.body.data.netMinor);
    await request(app).post(api('/payroll/runs')).set(A()).send({ month: '2026-09' }).expect(409);
  });

  it("shows the payroll office one person's salary, advances and year of payslips", async () => {
    const res = await request(app).get(api(`/payroll/staff/${employeeId}`)).set(A()).expect(200);
    const pay = res.body.data as {
      structure: { accountNumber: string | null } | null;
      monthly: { grossMinor: number; netMinor: number; earnings: { code: string }[]; deductions: { code: string }[] } | null;
      advances: { outstandingMinor: number }[];
      year: number;
      years: number[];
      payslips: { status: string; netMinor: number }[];
      yearTotals: { payslips: number; netMinor: number };
    };
    expect(pay.structure?.accountNumber).toBe('PK00TEST');
    // A full month on the structure: 140000 gross, less PF 5000 and tax 14000 (no advance instalment).
    expect(pay.monthly).toMatchObject({ grossMinor: 140000, netMinor: 121000 });
    expect(pay.monthly!.earnings.map((e) => e.code)).toEqual(['HRA']);
    expect(pay.advances.map((a) => a.outstandingMinor)).toEqual([15000]);
    expect(pay).toMatchObject({ year: 2026, years: [2026] });
    expect(pay.payslips).toHaveLength(1);
    expect(pay.payslips[0]!.status).toBe('PUBLISHED');
    expect(pay.yearTotals).toMatchObject({ payslips: 1, netMinor: pay.payslips[0]!.netMinor });

    const earlier = await request(app).get(api(`/payroll/staff/${employeeId}?year=2025`)).set(A()).expect(200);
    expect(earlier.body.data).toMatchObject({ year: 2025, years: [2026, 2025], payslips: [], yearTotals: { payslips: 0, netMinor: 0 } });

    const token = await signIn(teacherEmail, 'Teacher123!');
    await request(app).get(api(`/payroll/staff/${employeeId}`)).set(auth(token)).expect(403);
  });

  it('shows staff their own payslips and nobody else’s', async () => {
    const token = await signIn(teacherEmail, 'Teacher123!');
    const mine = await request(app).get(api('/payroll/my-payslips')).set(auth(token)).expect(200);
    expect(mine.body.data.items).toHaveLength(1);
    const slipId = mine.body.data.items[0]._id as string;
    await request(app).get(api(`/payroll/my-payslips/${slipId}`)).set(auth(token)).expect(200);
    // The school admin has no payslip of their own, so the same id is not theirs to read this way.
    await request(app).get(api(`/payroll/my-payslips/${slipId}`)).set(A()).expect(404);
    // And a teacher can't use the payroll office's endpoints.
    await request(app).get(api(`/payroll/runs/${runId}`)).set(auth(token)).expect(403);
  });
});

describe('Finance ledger', () => {
  it('records and voids expenses, and summarises fees, income and expenses without double counting', async () => {
    const utilities = (await request(app).post(api('/finance/categories')).set(A()).send({ name: 'Utilities', type: 'EXPENSE' }).expect(201)).body.data._id;
    const donations = (await request(app).post(api('/finance/categories')).set(A()).send({ name: 'Donations', type: 'INCOME' }).expect(201)).body.data._id;
    const today = new Date().toISOString();

    await request(app).post(api('/finance/entries')).set(A()).send({ type: 'INCOME', categoryId: utilities, amountMinor: 100, date: today, description: 'Wrong type' }).expect(400);
    const wrong = await request(app).post(api('/finance/entries')).set(A()).send({ type: 'EXPENSE', categoryId: utilities, amountMinor: 99999, date: today, description: 'Typo' }).expect(201);
    await request(app).post(api(`/finance/entries/${wrong.body.data._id}/void`)).set(A()).send({ reason: 'Typo in amount' }).expect(200);
    await request(app).post(api('/finance/entries')).set(A()).send({ type: 'EXPENSE', categoryId: utilities, amountMinor: 4000, date: today, description: 'Electricity' }).expect(201);
    await request(app).post(api('/finance/entries')).set(A()).send({ type: 'INCOME', categoryId: donations, amountMinor: 2500, date: today, description: 'Alumni gift' }).expect(201);

    const summary = await request(app).get(api('/finance/summary?months=1')).set(A()).expect(200);
    const month = summary.body.data.months[0];
    expect(month.feeIncomeMinor).toBe(13000);
    expect(month.otherIncomeMinor).toBe(2500);
    // Electricity 4000 (the voided entry is excluded); salary postings are dated today too.
    expect(month.expenseMinor).toBeGreaterThanOrEqual(4000);
    expect(summary.body.data.byCategory.some((c: { name: string }) => c.name === 'Salaries')).toBe(true);
  });
});
