/**
 * Generates the mobile theme from the web's OKLCH tokens (frontend/src/app/globals.css),
 * so both apps share one palette. NativeWind wants RGB channel triples in CSS variables;
 * native props (tab bar, icons, status bar) want hex. Both come from here.
 *
 *   npm run theme   → writes src/global.css and src/lib/theme-tokens.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';

const TOKENS = ['background', 'foreground', 'card', 'card-foreground', 'primary', 'primary-foreground', 'secondary', 'muted', 'muted-foreground', 'accent', 'accent-foreground', 'border', 'input', 'ring', 'destructive', 'destructive-foreground', 'destructive-soft', 'success', 'success-foreground', 'success-soft', 'warning', 'warning-foreground', 'warning-soft', 'info', 'info-foreground', 'info-soft', 'chart-1'];

const css = readFileSync(new URL('../../frontend/src/app/globals.css', import.meta.url), 'utf8');
const block = (selector) => css.slice(css.indexOf(`${selector} {`), css.indexOf('}', css.indexOf(`${selector} {`)));
// Translucent tokens (dark borders: `oklch(1 0 0 / 12%)`) keep their alpha; they're flattened over the background below.
const parse = (text) =>
  Object.fromEntries(
    [...text.matchAll(/--([a-z0-9-]+):\s*oklch\(([\d.]+)\s+([\d.]+)\s+([\d.]+)(?:\s*\/\s*([\d.]+)%)?\)/g)].map((m) => [
      m[1],
      [+m[2], +m[3], +m[4], m[5] === undefined ? 1 : +m[5] / 100],
    ]),
  );

function toRgbOpaque([L, C, h]) {
  const a = C * Math.cos((h * Math.PI) / 180), b = C * Math.sin((h * Math.PI) / 180);
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3, m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3, s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s, -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s, -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s]
    .map((v) => Math.round(Math.min(1, Math.max(0, v <= 0.0031308 ? 12.92 * v : 1.055 * v ** (1 / 2.4) - 0.055)) * 255));
}
let currentBackground = null;
/** RGB for a token; a translucent one is composited over the theme's background, since RN colours here are opaque. */
function toRgb(token) {
  const rgb = toRgbOpaque(token);
  const alpha = token[3] ?? 1;
  if (alpha >= 1 || !currentBackground) return rgb;
  const bg = toRgbOpaque(currentBackground);
  return rgb.map((c, i) => Math.round(c * alpha + bg[i] * (1 - alpha)));
}
const hex = (rgb) => '#' + rgb.map((c) => c.toString(16).padStart(2, '0')).join('');

const themes = { light: parse(block(':root')), dark: parse(block('.dark')) };
// Web derives these from other tokens; mirror that here.
for (const [name, t] of Object.entries(themes)) t['warning-ink'] = name === 'light' ? t['warning-foreground'] : t.warning;

const names = [...TOKENS, 'warning-ink'];
const cssVars = (t) => (currentBackground = t.background, names).map((n) => `    --${n}: ${toRgb(t[n]).join(' ')};`).join('\n');
writeFileSync(new URL('../src/global.css', import.meta.url), `/* Generated by scripts/gen-theme.mjs from the web's tokens — do not edit by hand (npm run theme). */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
${cssVars(themes.light)}
  }
  @media (prefers-color-scheme: dark) {
    :root {
${cssVars(themes.dark)}
    }
  }
}
`);
const camel = (n) => n.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const tsObj = (t) => (currentBackground = t.background, names).map((n) => `    ${camel(n)}: '${hex(toRgb(t[n]))}',`).join('\n');

// School palettes (`[data-palette='x']` blocks on the web): only the accent
// family moves, so only those tokens are emitted — hex for native props, and
// RGB triples for NativeWind's vars() at the app root.
const PALETTE_TOKENS = ['primary', 'primary-foreground', 'accent', 'accent-foreground', 'ring', 'chart-1'];
const paletteKeys = [...new Set([...css.matchAll(/\[data-palette='([a-z]+)'\]/g)].map((m) => m[1]))];
const palettes = Object.fromEntries(
  paletteKeys.map((key) => [key, { light: parse(block(`[data-palette='${key}']`)), dark: parse(block(`.dark [data-palette='${key}']`)) }]),
);
for (const [key, p] of Object.entries(palettes))
  for (const scheme of ['light', 'dark'])
    for (const n of PALETTE_TOKENS) if (!p[scheme][n]) throw new Error(`palette ${key} (${scheme}) is missing --${n}`);
const paletteHex = (p) => PALETTE_TOKENS.map((n) => `      ${camel(n)}: '${hex(toRgb(p[n]))}',`).join('\n');
const paletteVars = (p) => PALETTE_TOKENS.map((n) => `      '--${n}': '${toRgb(p[n]).join(' ')}',`).join('\n');
const paletteTs = (fn) =>
  paletteKeys.map((k) => `  ${k}: {\n    light: {\n${fn(palettes[k].light)}\n    },\n    dark: {\n${fn(palettes[k].dark)}\n    },\n  },`).join('\n');
writeFileSync(new URL('../src/lib/theme-tokens.ts', import.meta.url), `// Generated by scripts/gen-theme.mjs from the web's tokens — do not edit by hand.
export const THEME_TOKENS = {
  light: {
${tsObj(themes.light)}
  },
  dark: {
${tsObj(themes.dark)}
  },
} as const;
export type ThemeTokens = { [K in keyof (typeof THEME_TOKENS)['light']]: string };

/** School palettes, from the web's [data-palette] blocks: the accent tokens each one changes. */
export const PALETTE_TOKENS = {
${paletteTs(paletteHex)}
} as const;
/** The same palettes as CSS variables (RGB triples), for NativeWind's vars() at the app root. */
export const PALETTE_VARS = {
${paletteTs(paletteVars)}
} as const;
export type PaletteKey = keyof typeof PALETTE_TOKENS;
`);
console.log('theme written:', names.length, 'tokens × 2 schemes,', paletteKeys.length, 'school palettes');
